services:
  php-fpm:
    image: pplulee/expense-php:latest
    volumes:
      - .env:/var/www/html/.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - expense-network
    healthcheck:
      test: [ "CMD", "test", "-f", "/var/run/php/php-fpm.pid" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:${WEB_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - expense-network
    restart: always

  mariadb:
    image: mariadb:latest
    volumes:
      - ./data/mariadb/data:/var/lib/mysql
      - ./data/mariadb/conf:/etc/mysql/conf.d
    env_file:
      - .env
    networks:
      - expense-network
    restart: always
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-h", "localhost", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  expense-network:
    driver: bridge
